version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: express_db
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=DADN252
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: express_backend
    ports:
      - "3069:3069"
    environment:
      - PORT=3069
      - REDIS_URL=redis://redis:6379
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - DATABASE_URL=mysql://root:123456@db:3306/DADN252
    depends_on:
      - redis
      - elasticsearch
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: express_redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: express_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    mem_limit: 1g

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: express_kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus
    container_name: express_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: express_grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
